<?php
/**
 * Mediego
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mediego
 * @package    Mediego_Recommendations
 * @author     Orinoko <contact@orinoko.fr>
 * @copyright  Copyright (c) 2014-2015 Mediego (http://mediego.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    $_enabled = Mage::helper('mediego_recommendations')->isOpengraphEnabled();

    if ($_enabled && $this->getRequest()->getModuleName() == 'catalog'
                  && $this->getRequest()->getControllerName() == 'product'):
        $_product = Mage::registry('current_product');

        // add minimal price support for tier priced products
        if($_product->getFinalPrice() == 0) {
            $_product = Mage::getModel("catalog/product")->getCollection()
                ->addAttributeToSelect(Mage::getSingleton("catalog/config")->getProductAttributes())
                ->addAttributeToFilter("entity_id", $_product->getId())
                ->setPage(1, 1)
                ->addMinimalPrice()
                ->addFinalPrice()
                ->load()
                ->getFirstItem();
        }

        $_storeCcySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>

    <?php if ($_product): ?>
        <meta property="og:type" content="product"/>
        <meta property="og:url" content="<?php echo $_product->getProductUrl(); ?>"/>
        <meta property="og:title" content="<?php echo htmlspecialchars($_product->getName()) ?>" />
        <meta property="product:name" content="<?php echo htmlspecialchars($_product->getName()) ?>" />
        <meta property="product:original_price:amount" content="<?php echo number_format($_product->getPrice(), 2, ".", " ") ?>" />
        <meta property="product:original_price:currency" content="<?php echo $_storeCcySymbol ?>" />
        <meta property="product:price:amount" content="<?php echo number_format($_product->getFinalPrice() == 0 ? $_product->getMinimalPrice() : $_product->getFinalPrice(), 2, ".", " ") ?>" />
        <meta property="product:price:currency" content="<?php echo $_storeCcySymbol ?>" />
        <meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(210); ?>" />
    <?php endif; ?>
<?php endif; ?>
